### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ikrammohamdi** [ayman-jamal/Arabic-Sign-Language-Translation-System#2]
Utils.plots could not be resolved

**Comment by Mohad009** [comment]
> Utils.plots could not be resolved

I have similar issue
ModuleNotFoundError: No module named 'utils.plots'

i installed yolov5 and it fix this issue.
then, from yolov5.utils.plots import Annotator, colors, save_one_box
however I ran into another problem .
Traceback (most recent call last):
  File "D:\Arabic-Sign-Language-Translation-System\Esm3ny.py", line 72, in load_image
    model = torch.hub.load('ultralytics/yolov5', 'custom', path=model_name,force_reload=True)
  File "C:\Users\mralh\.conda\envs\test\lib\site-packages\torch\hub.py", line 647, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Users\mralh\.conda\envs\test\lib\site-packages\torch\hub.py", line 676, in _load_local
    model = entry(*args, **kwargs)
  File "C:\Users\mralh/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 135, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
  File "C:\Users\mralh/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 103, in _create
    raise Exception(s) from e
Exception: [Errno 2] No such file or directory: 'best_final_2.pt'. Cache may be out of date, try `force_reload=True` or see https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading for help.
